# Generated by Django 4.2.6 on 2023-10-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LocalShopApp", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Phone", "Phone"),
                    ("Audio", "Audio"),
                    ("Accessory", "Accessory"),
                    ("Wearable", "Wearable"),
                ],
                default="Phone",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
