# Generated by Django 4.2.6 on 2023-10-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LocalShopApp", "0005_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
