# Generated by Django 4.2.6 on 2023-10-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LocalShopApp", "0006_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="Description", max_length=500),
        ),
    ]
